version: '3.1'

services:
  springboot:
    image: 291228166679.dkr.ecr.ap-south-1.amazonaws.com/myspringbootmongoapp:VERSION
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    ports:
      - 8081:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - springappnetwork  
   

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    external: true
    
networks:
  springappnetwork:
    external: true
